### ISSUE TITLE
Setup CI for unit tests

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-pkcs12#8]
Potential checks:

* go build 
* go test
* go lint
* go vet
* gofmt

**Comment by dgryski** [comment]
I suggest avoid golint as a CI test.  There are false positives and not even the standard library is lint-free.

**Comment by GeertJohan** [comment]
@dgryski  +1

**Comment by nathany** [comment]
May want to hold off on this because of #9. Is https://github.com/golang/crypto already tested by builders, see http://build.golang.org/?repo=golang.org%2fx%2fcrypto

**Comment by dgryski** [comment]
Depends on timeline for incorporation (if any) and effort required to add travis support (which is minimal).

**Comment by ahmetalpbalkan** [comment]
Yep we're working on it it's really no big deal.

**Comment by nathany** [comment]
True. If using [Travis CI](https://travis-ci.org/), my typical .travis.yml looks like:

```yaml
sudo: false
language: go

go:
  - 1.4.2

os:
  - linux
  - osx

before_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -v ./...

notifications:
  email: false

branches:
  only:
    - master
```
